name: Alex Zevenbergen Blog
favicon: null
layout_spectrum: 0.1475
typography_spectrum: 0.15103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#22262f'
    - '#636c67'
    - '#94b3d2'
    - '#92a800'
  brandStrength: 0.1875
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
