name: Alex Zevenbergen Blog
favicon: null
layout_spectrum: 0.1475
typography_spectrum: 0.15103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6eef1'
    - '#6082af'
    - '#131e0f'
    - '#475766'
    - '#c6cdd3'
  brandStrength: 0.0625
  lightness: 0.0625
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
