name: Alex Zevenbergen Blog
favicon: null
layout_spectrum: 0.1475
typography_spectrum: 0.15103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0303'
    - '#fffffd'
    - '#454221'
    - '#b84736'
    - '#a6ae88'
  brandStrength: 0.3125
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
